package com.example.music.data.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data class representing a saved music track in the Supabase "saved_music" table.
 * Uses Kotlinx Serialization for Supabase Postgrest compatibility.
 */
@Serializable
data class SavedMusicItem(
    val id: Long? = null,              // auto-generated by Supabase
    @SerialName("track_id")
    val trackId: Long,
    val title: String,
    @SerialName("artist_name")
    val artistName: String,
    @SerialName("album_title")
    val albumTitle: String? = null,
    @SerialName("cover_url")
    val coverUrl: String? = null,
    @SerialName("preview_url")
    val previewUrl: String,
    val duration: Int = 0,
    @SerialName("is_favorite")
    val isFavorite: Boolean = false,
    @SerialName("created_at")
    val createdAt: String? = null       // auto-generated by Supabase
) {
    /**
     * Convert this Supabase record back into the app's Track model.
     */
    fun toTrack(): Track {
        return Track(
            id = trackId,
            title = title,
            preview = previewUrl,
            duration = duration,
            artist = Artist(id = 0, name = artistName),
            album = Album(
                id = 0,
                title = albumTitle ?: "Saved",
                coverMedium = coverUrl
            ),
            isFavorite = isFavorite
        )
    }

    companion object {
        /**
         * Convert an app Track model into a Supabase-compatible SavedMusicItem.
         */
        fun fromTrack(track: Track, favorite: Boolean = false): SavedMusicItem {
            return SavedMusicItem(
                trackId = track.id,
                title = track.title,
                artistName = track.artist.name,
                albumTitle = track.album.title,
                coverUrl = track.album.coverMedium,
                previewUrl = track.preview,
                duration = track.duration,
                isFavorite = favorite
            )
        }
    }
}
